name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Windows Config
        run: |
          git config --system core.longpaths true
          echo "Enabled long paths in git"

          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          echo "Enabled long paths in registry"

          $git_link = "C:\Program Files\Git\usr\bin\link.exe"
          if (Test-Path $git_link) {
              Rename-Item $git_link "_link.exe"
          }
          echo "Removed link.exe in git"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.29
          arch: x64
          sdk: 10.0.19041.0

      - name: Checkout self
        uses: actions/checkout@v6

      - name: Checkout target
        uses: actions/checkout@v6
        with:
          repository: uutils/coreutils
          ref: refs/tags/0.5.0
          path: coreutils

      - name: Copy config file
        shell: bash
        run: |
          mkdir -p coreutils/.cargo
          cp -f .cargo/config.toml coreutils/.cargo

      - name: Build
        shell: bash
        run: |
          cd coreutils
          rm -f Cargo.lock
          cargo update
          # cargo b -r --no-default-features --features "cat cp ln ls mkdir mv rm touch yes"
          cargo b -r -p uu_mkdir


      - name: Archive
        uses: actions/upload-artifact@v5
        with:
          name: coreutils_${{ matrix.os }}
          path: |
            coreutils/target/release/*.exe
